[project]
name = "aiogram-tool"
version = "1.2.2"
description = "Tools which doing work with aiogram simple"
authors = [
    {name = "Vlad_shayzi1",email = "tecnomega@mail.ru"}
]   
readme = "README.md"
license = "MIT"
requires-python = ">=3.11"
dependencies = [
    "aiogram==3.29.1",
    "redis>=8.0.0",
]
keywords = [
    "aiogram",
    "rate",
    "throttling",
    "limit",
    "dependency-injection",
    "depends",
    "cooldown",
    "delay",
    "DI",
    "callback",
    "data",
    "long"
]

[project.urls]
Repository = "https://github.com/shayzi3/aiogram_tool"
Contributing = "https://github.com/shayzi3/aiogram_tool/blob/master/CONTRIBUTING.md"

[dependency-groups]
dev = [
    "aiohttp-socks>=0.11.0",
    "pre-commit>=4.6.2",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.5",
]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "B", "UP"]

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["aiogram_tool.tools.depend.Depends", "aiogram_tool.tools.depend.depend.Depends"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"